---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress-01-aws-upstream
  namespace: default
spec:
  ingressClassName: external-nginx
  rules:
    - host: 01-aws-upstream-argocd.panwang.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loki-01-aws-upstream 
                port:
                  number: 80

