apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - namespace.yaml

helmCharts:
- name: prometheus
  version: 25.30.1
  repo: https://prometheus-community.github.io/helm-charts
  includeCRDs: true
  valuesFile: values.yaml
  namespace: monitoring
  releaseName: prometheus
