
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    # helm:
    #   parameters:
    #     - name: installCRDs
    #       value: "true"
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 45.6.0
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
