apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-test
  # namespace: argocd
  namespace: default
spec:
  destination:
    # namespace: argocd
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: test
    repoURL: https://github.com/maxxam123/upstream.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
