---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-02-aws-downstream
  # namespace: argocd
  namespace: default
spec:
  destination:
    namespace: ingress
    server: https://HTTPS
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: 04_git/aws/10_eks/02-aws-downstream/01_bootstrap/nginx/charts/ingress-nginx
    repoURL: 'https://github.com/maxxam123/gitops.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
