apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-upstream
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps
    repoURL: https://github.com/maxxam123/upstream.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: app-bootstrap
#   namespace: argocd
# spec:
#   destination:
#     namespace: argocd
#     server: https://kubernetes.default.svc
#   project: default
#   source:
#     path: 04_git/aws/01-upstream/01-aws-upstream/01_bootstrap/cert-manager
#     repoURL: https://github.com/maxxam123/gitops.git
#     targetRevision: HEAD
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
#       - ServerSideApply=true
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: app-projects
#   namespace: argocd
# spec:
#   destination:
#     namespace: argocd
#     server: https://kubernetes.default.svc
#   project: default
#   source:
#     path: 04_git/aws/01-upstream/01-aws-upstream/03_projects
#     repoURL: https://github.com/maxxam123/gitops.git
#     targetRevision: HEAD
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
#       - ServerSideApply=tru
