apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-2
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: 04_git/aws/02_aws_eks/02_monitor/01_prometheus
    repoURL: https://github.com/maxxam123/gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
