---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-secret-03-aws-eks
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore-aws
    kind: SecretStore
  target:
    name: loki-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: loki-secret
