apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-remote-cluster
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://HTTPS
  project: default
  source:
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: "true"
    repoURL: https://charts.jetstack.io
    targetRevision: 'v1.3.1'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-remote-cluster-02-aws-vpc
  namespace: argocd
spec:
  destination:
    namespace: prometheus
    server: https://HTTPS
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 45.6.0
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
