loki:
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage_config:
    aws:
      region: eu-central-1
      bucketnames: FILE-loki-bucket
      s3forcepathstyle: false
  ingester:
    chunk_encoding: slappy
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 672h
  compactor:
    retention_enabled: true
    delete_request_store: s3
  rules:
    enable_api: true
    storage:
      type: s3
      s3:
        region: eu-central-1
        bucketname: FILE-loki-bucket
        s3forcepathstyle: false
      alertmanager_url: http://prom:9003
  querrier:
    max_concurrent: 4
  storage:
    type: s3
      bucketNames:
        chunks: FILE-loki-bucket
        ruler: FILE-loki-bucket
      s3:
        region: eu-central-1
