apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-02-aws-eks
  namespace: argocd
spec:
  destination:
    namespace: ingress
    server: https://kubernetes.default.svc
  project: default
source:
    path: 04_git/aws/10_eks/02-aws-eks/01_bootstrap/nginx/charts/ingress-nginx
    repoURL: 'https://github.com/maxxam123/gitops.git'
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      
