on:
 push:
   branches:
   - main
   paths:
   - '01_infraaaaaaaaaa/01-upstream/aws/01-aws-upstream/terraform.tfvars'
   - '01_infraaaaaaaaaa/01-upstream/aws/01-aws-upstream/gitops'

env:
 AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }} 
 AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }} 
 GITHUB: ${{ secrets.GITHUB }} 
 AWS_VELERO_01: ${{ secrets.VELERO01 }} 
 AWS_VELERO_02: ${{ secrets.VELERO02 }} 
 AWS_VELERO_03: ${{ secrets.VELERO03 }} 


jobs:
 build:
   name: "test"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       working-directory: 01_infra/01-upstream/