on:
 push:
   branches:
   - main
   paths:
   - 'stuff'

env:
 AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
 GITHUB: ${{ secrets.GITHUB }}

jobs:
 build:
   name: "test"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       working-directory: 01_infra/10_eks/aws/03_aws_eks/
   steps:
     - name: test
       uses: actions/checkout@v3

     - name: apply app-of-apps
       run: |
         pip install awscli
         aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
         aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
         aws configure set default.region "eu-central-1"
         
         curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
         chmod +x kubectl
         mkdir -p ~/.local/bin
         cp ./kubectl ~/.local/bin/kubectl
         
         aws eks update-kubeconfig --region eu-central-1 --name demo-staging
         echo TWO
         ./kubectl create secret generic -n velero velero-secret --from-file=aws=$VELERO
         
