---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-aws
spec:
  provider:
    aws:
      service: SecretManager
      region: eu-central-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: username
          secretAccessKeySecretRef:
            name: awssm-secret
            key: password
---
apiVersion: external-secrets.io/v1beta1
kind: external-secrets
metadata:
  name: remote-repo
    labels:
      acme.org/owned-by: "q-team"
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore-aws
    kind: SecretStore
  target:
    name: aws-external-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: private-repo-2
