---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-aws
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: username
          secretAccessKeySecretRef:
            name: awssm-secret
            key: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: remote-repo
  labels:
    argocd.argoproj.io/secret-type: "repository"
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore-aws
    kind: SecretStore
  target:
    name: aws-external-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: private-repo-2
