apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-secret
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: remote-repo
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: private-repo-2
