apiVersion: v1
kind: Secret
metadata:
  name: 02_aws_eks
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: 02_aws_eks
  server: HTTPS:443
  config: |
    {
      "bearerToken": "TOKEN",
      "tlsClientConfig": {
        "serverName": "kubernetes.default.svc",
        "ca": "CERTIFICATE"
      }
    }
